--- #YAML:1.0
name:                WebDyne-Chain
version:             1.043
abstract:            ~
license:             gpl
author:              
    - Andrew Speer <andrew@webdyne.org>
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    WebDyne:                       
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
