--- #YAML:1.0
name:               WebDyne-Chain
version:            1.050
abstract:           WebDyne chaining module, allows extension of base WebDyne class
author:
    - Andrew Speer <andrew@webdyne.org>
license:            gpl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    WebDyne:  0
resources:
    homepage:  http://webdyne.org
    license:   http://www.gnu.org/licenses/gpl.html
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
